### ISSUE TITLE
getting a reference to the global require object

### ISSUE THREAD

**Issue by daenenk** [ldaniels528/means-js#1]
I tried 

``` scala
val require = scala.scalajs.js.Dynamic.global.require.asInstanceOf[org.scalajs.nodejs.NodeRequire]
```

which works when I launch my code with `run` in sbt.
But when I launch my code with `node` from command line, `require` is not defined.

**Comment by ldaniels528** [comment]
I've run into the same problems, and I'm not sure why we can't get a reference to require in the traditional way. As a result, I've been using a bootstrap JavaScript launcher, as shown in the integration guidance:

https://github.com/ldaniels528/scalajs-nodejs#node_integration
