### ISSUE TITLE
process.hrtime needs to take an optional arg

### ISSUE THREAD

**Issue by aappddeevv** [ldaniels528/means-js#10]
process.hrtime can take no args or an arg that is the result of a previous call of hrtime. This allows you to measure the time to run a function.

https://nodejs.org/api/process.html#process_process_hrtime_time

Maybe something like: `def hrtime(previous: UndefOr[Array[Int]] = js.undefined): Array[Int] = js.native` or provide another func with a different arity.

**Comment by ldaniels528** [comment]
Resolved with v0.4.0pre4
