### ISSUE TITLE
UndefinedBehaviourError when using __dirname

### ISSUE THREAD

**Issue by MHOOO** [ldaniels528/means-js#12]
When using 

    io.scalajs.nodejs.global.__dirname

I get an UndefinedBehaviorError. I use the following dependencies in my project:
"io.scalajs.npm" %%% "express" % "0.4.0-pre3"
"io.scalajs.npm" %%% "express-ws" % "0.4.0-pre3"
"io.scalajs.npm" %%% "body-parser" % "0.4.0-pre3"

Any Idea on what I am doing wrong?

**Comment by ldaniels528** [comment]
I can't see that you're doing anything wrong. I've quickly put together something that should help:

https://github.com/scalajs-io/examples

**Comment by ldaniels528** [comment]
Still having issues?

**Comment by MHOOO** [comment]
To be honest, for now, I've worked around the issue by using Path.resolve().
Should I come across this again, I'll update this issue and see that I can
create a minimal Test case.

For now this is solved for me! Thanks.

Am 19.04.2017 21:17 schrieb "Lawrence Daniels" <notifications@github.com>:
