### ISSUE TITLE
module layout

### ISSUE THREAD

**Issue by aappddeevv** [ldaniels528/means-js#13]
When using some of the modules, I find that somethings feel awkward. Maybe I'm not doing it correctly.

Example: Using the fs module, I need to access the Fs object to access the `access` function. I would have expected that `fs.access(...)` would work, but its really fs.Fs.access(...)`. That's a bit different than my expectations.

**Comment by ldaniels528** [comment]
Actually, you would just use the 'Fs' object directly (without including the package name): 

```scala
      import io.scalajs.nodejs.fs._

      val file1 = "./src/test/resources/fileB1.txt"
      val file2 = "./src/test/resources/fileB2.txt"

      val readable = Fs.createReadStream(file1)
      val writable = Fs.createWriteStream(file2)
      readable.pipe(writable)
      writable.onFinish { () =>
        info("Comparing file sizes:")
        info(s"$file1 is ${Fs.statSync(file1).size} bytes")
        info(s"$file2 is ${Fs.statSync(file2).size} bytes")
        assert(Fs.statSync(file1).size == Fs.statSync(file2).size)
      }
```

**Comment by aappddeevv** [comment]
Ok. I think the expectation was that if I `import io.scaljas.nodejs.fs` then I could do `fs.access(..)` vs the extra hop through `Fs` which to me was implied with the `fs`. I only mention this because I scan node.js source code for how they use the API and they always prefix with just `fs` so I hit a mental pause during development.
