### ISSUE TITLE
Dead Links in README under 'Third-party Modules'

### ISSUE THREAD

**Issue by pcraddick** [ldaniels528/means-js#18]
Three (3) referenced repos seem not to exist (404 returned):
- socket.io (https://github.com/scalajs-io/socket.io)
- socket.io-client (https://github.com/scalajs-io/socket.io-client)
- kafka-rest (https://github.com/scalajs-io/kafka-rest)

**Comment by ldaniels528** [comment]
thanks, I'll update them.

**Comment by pcraddick** [comment]
I'm sure you're busy with other things ... but any ETA on this?

**Comment by guilgaly** [comment]
Sorry to be that guy, but... Is there any news on this?

**Comment by ldaniels528** [comment]
LOL, no worries. Yes, I've been slacking a bit... I hope to have the issue resolved by this Sunday night (8/27).

**Comment by pcraddick** [comment]
knock knock

**Comment by ldaniels528** [comment]
I've removed the broken links.

My socket.io binding will be replaced by the (soon to be released) engine.io binding.
