### ISSUE TITLE
tests + code formatting

### ISSUE THREAD

**Issue by rmmeans** [ldaniels528/means-js#5]
Wow, great project ! 🎉 

I'd like to contribute some to this for our needs, but I noticed that the tests currently don't compile. 
Wanted to see what your plans were on getting the tests working again, and then having them run against travis or similar so PR's can be validated?

Also, wasn't sure your thoughts on using scalafmt or similar so the code style can be universally applied by all contributors?

**Comment by ldaniels528** [comment]
I'd love to have some additional contributors, and it shouldn't take much to fix the few tests that don't compile as I think most of them are the tests that attempt to connect to server instances (e.g. Kafka, MongoDB and others). What I really need to do is either mock these or use embedded variants of these services. Scalafmt is also a great idea for keeping the code-style uniform. It would be great if setting up scalafmt were your first official contribution. Could you submit a PR for that?

**Comment by rmmeans** [comment]
Any special config you had to setup to run the tests? This repo is so large in the number of sub-projects that my env is falling over in the middle of the test runs with `java.lang.OutOfMemoryError: Java heap space`.   

Just curious what your experiences have been with this. The size of this repo does make me wonder though if it shouldn't be split into some smaller projects with isolated repos? I would think at least a node & npm split might be nice.

**Comment by ldaniels528** [comment]
It's funny, I've actually already started work to that end: https://github.com/scalajs-io

As far as special config, I've increased the amount of maximum memory that SBT can use to 4GB; however, with the project broken into smaller pieces this will no longer be necessary.

**Comment by rmmeans** [comment]
ha! outstanding. good to know as we will primarily be using the nodeJs bindings for our scalaJS AWS Lambda functions 👍

**Comment by ldaniels528** [comment]
Awesome! I'm going to try to split out the remaining modules this evening, and merge your changes into the new project(s).
