### ISSUE TITLE
add this project to https://www.scala-js.org/libraries/facades.html 

### ISSUE THREAD

**Issue by aappddeevv** [ldaniels528/means-js#8]
Exactly what I was looking for.

**Comment by ldaniels528** [comment]
Thanks! Please provide some feedback once you've had a chance to play with it.

**Comment by aappddeevv** [comment]
Will do.

It's not clear that people understand how important this project is given
that node/js is really the next jvm. There will only a few large scale
platforms to run on since the world cannot manage more than a few at a time
given the cost of each platform.

**Comment by ldaniels528** [comment]
My sincere hope is that this project can help drive adoption of Scala.js on Node.js. We'll see!

**Comment by scalajs-io** [comment]
Request made.
