### ISSUE TITLE
add node-fetch (or fetch-api)

### ISSUE THREAD

**Issue by aappddeevv** [ldaniels528/means-js#9]
Fetch is coming to es and then node per the es standard so it would be good to include it sooner since there is a node-fetch for node already that has the same api. Maybe this belongs under npms? I think the recent node.js update makes you wonder how to control the api exposure in this project against the LTS and most recent version of node out there...perhaps always just adhere to the most recent.

**Comment by ldaniels528** [comment]
I'll add it to the next release, which should be available by this weekend.

**Comment by aappddeevv** [comment]
You'll probably want to figure out which one polyfills the best. It's really only needed  for 6.x node servers vs 7.x I think. I'm not sure how it all gets mixed together. fetch-api may polyfill the smartest.

**Comment by ldaniels528** [comment]
I'll take a look at fetch-api, but for now, this one should suffice:

https://github.com/scalajs-io/node-fetch

**Comment by ldaniels528** [comment]
This module has been added.
